'use client';

import { ArrowUpRight, GitBranch, PackageOpen, Send, UploadCloud } from 'lucide-react';
import { useState } from 'react';
import AdminShell from '@/components/AdminShell';

const releases = [['Orbit CRM Pro', 'v2.4.0', 'Atualização publicada', 'Hoje'], ['Flow Bot', 'v1.8.2', 'Em revisão', 'Ontem'], ['Atlas ERP Cloud', 'v3.1.0', 'Agendada', '25 set']];

export default function ReleasesPage() {
  const [published, setPublished] = useState(false);
  return <AdminShell><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-[#36A5B4]">Delivery system</p><h1 className="mt-2 font-display text-4xl font-bold tracking-[-.05em]">Releases & updates.</h1><p className="mt-3 text-sm text-[#718096]">Publique versões, arquivos e atualizações para clientes com Product Key.</p></div><button onClick={() => setPublished(true)} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#1A202C] px-5 py-3 text-sm font-bold text-white"><UploadCloud size={17} /> Nova release</button></div>{published && <p className="mt-5 rounded-xl bg-[#E6FFFA] p-4 text-sm font-bold text-[#277C73]">Release criada como rascunho. O envio aos compradores será feito após publicação.</p>}<section className="mt-8 rounded-3xl border border-black/5 bg-white p-6 shadow-sm"><div className="grid gap-3">{releases.map(([product, version, status, date]) => <article key={version} className="flex flex-col justify-between gap-4 rounded-2xl border border-black/5 p-5 md:flex-row md:items-center"><div className="flex items-center gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#EFFFFF] text-[#1597A8]"><GitBranch size={19} /></span><div><p className="text-sm font-bold">{product} <span className="ml-2 font-mono text-xs text-[#1597A8]">{version}</span></p><p className="mt-1 text-xs text-[#718096]">{status} · {date}</p></div></div><div className="flex gap-2"><button className="rounded-full border border-black/10 p-2 text-[#718096]" aria-label="Ver release"><ArrowUpRight size={16} /></button><button className="inline-flex items-center gap-2 rounded-full bg-[#F8F9FA] px-4 py-2 text-xs font-bold"><Send size={14} /> Notificar compradores</button></div></article>)}</div></section><section className="mt-6 grid gap-5 md:grid-cols-3">{[['SemVer', 'Controle de versões consistente'], ['Entrega segura', 'Links privados e temporários'], ['Comunicação', 'Atualizações para compradores']].map(([title, text]) => <article key={title} className="rounded-2xl bg-[#1A202C] p-6 text-white"><PackageOpen size={19} className="text-[#9AE6B4]" /><h2 className="mt-6 font-display text-xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-[#CBD5E0]">{text}</p></article>)}</section></div></AdminShell>;
}
