'use client';

import { ArrowRight, Clock3, Gift, Mail, ShoppingCart } from 'lucide-react';
import { useState } from 'react';
import AdminShell from '@/components/AdminShell';

const abandoned = [['carla@agency.com', 'Orbit CRM Pro', 'US$ 129', 'há 42 min'], ['bruno@retail.io', 'Atlas ERP Cloud', 'US$ 299', 'há 2 h'], ['bia@startup.co', 'Flow Bot', 'US$ 179', 'há 5 h']];

export default function AbandonedCartsPage() {
  const [discount, setDiscount] = useState('SAVE10');
  const [sent, setSent] = useState<string | null>(null);
  return <AdminShell><div className="mx-auto max-w-7xl"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-[#36A5B4]">Recovery automation</p><h1 className="mt-2 font-display text-4xl font-bold tracking-[-.05em]">Carrinhos abandonados.</h1><p className="mt-3 text-sm text-[#718096]">Recupere oportunidades com desconto personalizado e sequência automática.</p></div><div className="mt-8 grid gap-4 md:grid-cols-3">{[['Em recuperação', '38'], ['Valor potencial', 'US$ 6.420'], ['Recuperados este mês', 'US$ 2.180']].map(([label, value]) => <article key={label} className="rounded-2xl border border-black/5 bg-white p-6 shadow-sm"><ShoppingCart size={19} className="text-[#36B7C9]" /><p className="mt-6 text-sm text-[#718096]">{label}</p><p className="mt-1 font-display text-3xl font-bold">{value}</p></article>)}</div><section className="mt-6 rounded-3xl border border-black/5 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h2 className="font-display text-2xl font-bold">Fila de recuperação</h2><p className="mt-2 text-sm text-[#718096]">Oferta enviada apenas para clientes com opt-in de comunicação.</p></div><div className="flex items-center gap-2"><Gift size={17} className="text-[#C05621]" /><input value={discount} onChange={(event) => setDiscount(event.target.value)} className="h-10 w-28 rounded-lg border border-black/10 px-3 text-xs font-bold" /></div></div><div className="mt-6 grid gap-3">{abandoned.map(([email, product, value, time]) => <div key={email} className="flex flex-col justify-between gap-4 rounded-2xl border border-black/5 p-5 md:flex-row md:items-center"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#FFFAF0] text-[#C05621]"><Clock3 size={17} /></span><div><p className="text-sm font-bold">{email}</p><p className="mt-1 text-xs text-[#718096]">{product} · {value} · {time}</p></div></div><button onClick={() => setSent(email)} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#1A202C] px-4 py-2.5 text-xs font-bold text-white"><Mail size={15} /> {sent === email ? 'Enviado' : 'Enviar oferta'} <ArrowRight size={14} /></button></div>)}</div></section></div></AdminShell>;
}
