import { ArrowUpRight, BarChart3, DollarSign, Mail, ShoppingCart, Users } from 'lucide-react';
import AdminShell from '@/components/AdminShell';

const metrics = [
  { label: 'Receita líquida', value: 'US$ 84.290', change: '+24,8%', icon: DollarSign },
  { label: 'Pedidos pagos', value: '428', change: '+18,4%', icon: ShoppingCart },
  { label: 'Leads capturados', value: '1.284', change: '+32,1%', icon: Users },
  { label: 'Ticket médio', value: 'US$ 196', change: '+8,7%', icon: BarChart3 }
];

const bars = [42, 58, 48, 70, 64, 82, 74, 96, 88, 108, 98, 124];

export default function AdminPage() {
  return <AdminShell><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-[#36A5B4]">Command center</p><h1 className="mt-2 font-display text-4xl font-bold tracking-[-.05em]">Visão geral do negócio.</h1><p className="mt-3 text-sm text-[#718096]">Faturamento, produtos e relacionamento em uma única leitura.</p></div><span className="rounded-full bg-[#E6FFFA] px-4 py-2 text-xs font-bold text-[#277C73]">Dados atualizados há 4 min</span></div><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, change, icon: Icon }) => <article key={label} className="rounded-2xl border border-black/5 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wider text-[#A0AEC0]">{label}</p><Icon size={18} className="text-[#36B7C9]" /></div><p className="mt-7 font-display text-3xl font-bold">{value}</p><p className="mt-2 text-xs font-bold text-[#38A169]">{change} no período</p></article>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-3xl border border-black/5 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#A0AEC0]">Performance</p><h2 className="mt-2 font-display text-2xl font-bold">Receita por mês</h2></div><button className="inline-flex items-center gap-2 text-xs font-bold text-[#1597A8]">Exportar BI <ArrowUpRight size={15} /></button></div><div className="mt-8 flex h-56 items-end gap-2 border-b border-l border-black/10 px-4 pb-0">{bars.map((height, index) => <div key={index} className="group flex flex-1 flex-col items-center justify-end gap-2"><span className="w-full rounded-t-lg bg-[#36B7C9] transition group-hover:bg-[#1A202C]" style={{ height }} /><small className="-mb-6 text-[10px] text-[#A0AEC0]">{['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'][index]}</small></div>)}</div></section><section className="rounded-3xl bg-[#1A202C] p-7 text-white shadow-glass"><Mail size={20} className="text-[#9AE6B4]" /><h2 className="mt-8 font-display text-2xl font-bold">Marketing em movimento.</h2><p className="mt-3 text-sm leading-6 text-[#CBD5E0]">3 campanhas ativas e 214 clientes aguardando novidades.</p><div className="mt-8 h-2 rounded-full bg-white/10"><div className="h-2 w-[72%] rounded-full bg-[#9AE6B4]" /></div><p className="mt-3 text-xs text-[#A0AEC0]">72% da meta mensal</p></section></div></div></AdminShell>;
}
