import { Instagram, Linkedin, Mail, ShieldCheck } from 'lucide-react';
import Link from 'next/link';
import LanguageSelector from '@/components/LanguageSelector';
import { useLanguage } from '@/components/LanguageContext';

export default function PublicShell({ children }: Readonly<{ children: React.ReactNode }>) {
  const { translate } = useLanguage();

  return (
    <main className="min-h-screen bg-[#F8F9FA] text-[#1A202C]">
      <nav className="border-b border-black/5 bg-[#F8F9FA]/90 px-6 py-5 backdrop-blur-xl lg:px-10">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-6"><Link href="/" className="flex items-center gap-3 font-display text-lg font-bold tracking-tight"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#1A202C] text-sm text-white">K.</span> KELVEN<span className="font-normal text-[#A0AEC0]">/STUDIO</span></Link><div className="hidden items-center gap-7 text-sm font-semibold text-[#718096] md:flex"><Link href="/" className="hover:text-[#1A202C]">{translate('home')}</Link><Link href="/dashboard" className="hover:text-[#1A202C]">{translate('portfolio')}</Link><Link href="/contato" className="hover:text-[#1A202C]">{translate('contact')}</Link></div><div className="flex items-center gap-2"><LanguageSelector /><Link href="/checkout" aria-label="Abrir compras" className="rounded-full border border-black/10 bg-white px-4 py-2 text-xs font-bold transition hover:bg-[#1A202C] hover:text-white">{translate('buy')}</Link></div></div>
      </nav>
      {children}
      <footer className="border-t border-black/5 bg-white px-6 py-12 lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><Link href="/" className="flex items-center gap-3 font-display text-lg font-bold tracking-tight"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#1A202C] text-sm text-white">K.</span> KELVEN/STUDIO</Link><p className="mt-4 max-w-xs text-sm leading-6 text-[#718096]">{translate('digitalProducts')}</p><div className="mt-5 flex gap-2"><a href="https://www.linkedin.com" aria-label="LinkedIn" className="rounded-full border border-black/10 p-2 text-[#718096] hover:text-[#1A202C]"><Linkedin size={15} /></a><a href="https://www.instagram.com" aria-label="Instagram" className="rounded-full border border-black/10 p-2 text-[#718096] hover:text-[#1A202C]"><Instagram size={15} /></a><a href="mailto:hello@kelven.studio" aria-label="E-mail" className="rounded-full border border-black/10 p-2 text-[#718096] hover:text-[#1A202C]"><Mail size={15} /></a></div></div><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#A0AEC0]">Produto</p><div className="mt-4 grid gap-3 text-sm text-[#718096]"><Link href="/dashboard">{translate('portfolio')}</Link><Link href="/checkout">{translate('buy')}</Link><Link href="/contato">{translate('contact')}</Link></div></div><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#A0AEC0]">Empresa</p><div className="mt-4 grid gap-3 text-sm text-[#718096]"><Link href="/contato">{translate('contact')}</Link><Link href="/termos-de-uso">Termos de uso</Link><Link href="/politica-de-privacidade">Privacidade</Link></div></div><div className="rounded-2xl bg-[#F8F9FA] p-5"><ShieldCheck size={20} className="text-[#36A5B4]" /><p className="mt-3 text-sm font-bold">Compra protegida</p><p className="mt-2 text-xs leading-5 text-[#718096]">SSL 256-bit, pagamentos processados por parceiros certificados e suporte humano.</p></div></div><div className="mx-auto mt-10 flex max-w-7xl flex-col justify-between gap-3 border-t border-black/5 pt-6 text-xs text-[#A0AEC0] md:flex-row"><span>© 2026 Kelven Studio</span><span>LGPD · PCI-DSS · Licenças comerciais</span></div></footer>
    </main>
  );
}
